[package]
name = "fand"
version = "0.0.2"
authors = ["Philip Rebohle <philip.rebohle@tu-dortmund.de>", "proegssilb <proegssilb@gmail.com"]
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
log = "0.4.14"
env_logger = "0.9.0"
